D={'CP':'COMPUTER PROGRAMMING','FCE':'FUNDAMETNALS OF COMPUTER ENGINNERING','PST':'PAKISTAN STUDIES','BEE':'BASIC ELECTRICAL ENGINEERING'}
D['F.ENG']='FUNCTIONAL ENGLISH'
print(D)
print(D.get('Chinese'))
print(D['CP'])
